baseURL="https://iota-iiits.tech"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "IOTA-website"
title = "IOTA"
handle = "Home"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = ""
name = "Home"
weight = 1
[[menu.main]]
URL = "projects"
name = "Projects"
weight = 2
[[menu.main]]
URL = "teams"
name = "Teams"
weight = 3
[[menu.main]]
URL = "members"
name = "Members"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.nav]]
URL = "/"
name = "Home"
weight=1
[[menu.nav]]
URL = "contact"
name = "Contact"
[params]
author = "IOTA"
contact_form_action = "https://submit-form.com/ugSusVqd"
custom_honeypot = "a_random_custom_name"
copyright = "Made By: "
description = "IOTA is the Projects Club of IIIT Sri City. We have collaborated with other organizations from different domains to work on projects or problem statements. We also conducts regular sessions, workshops and hacakthons in various CS related topics."
footer_content = ""
logo = "images/iota_logo.png"
logo_width = "100px"
[params.navigation_button]
enable = false
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/iota_iiits/"
title = "instagram"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/IOTA.IIITS/"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/IiitsIota"
title = "twitter"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/iota-iiits/"
title = "linkedin"
[[params.social]]
icon = "ti-youtube"
link = "https://youtube.com/channel/UCjgxVYzHDlEWZZbCrjC1JSA"
title = "youtube"
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/suryavardan-suresh-9116511a0"
names="Suryavardan  "
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/anurag-kumar-003904191/"
names="Anurag   "
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/piyush-kumar-8687a3191"
names="Piyush"
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/priyam-bajpai-1b564a1a0"
names="Priyam"
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/khushi-pathak-756a41196"
names="Khushi "
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/anuhya-sarabu-276525194"
names="Anuhya "
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/kajal-srivastava-082066199"
names="kajal"
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/sashidhar-motte-155726194"
names="Shashidar"
[[params.copyrights]]
icon="ti-linkedin"
link="https://www.linkedin.com/in/sampath-kumar-reddy-manam-6516751a0"
names="Sampath"
